import type { Metadata } from "next";
import { Geist, Geist_Mono, Yuji_Syuku } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 毛筆フォント
const yujiSyuku = Yuji_Syuku({
  variable: "--font-yuji",
  weight: "400",
  subsets: ["latin"],
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yujiSyuku.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
